services:
  mysql:
    image: mysql
    container_name: mysql-user-management
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
volumes:
  mysql-data:
    driver: local
networks:
  mysql-network:
    driver: bridge
